Desktop/pilkanozna/Wydarzenia/urls.py
from django.conf.urls import url

from . import views

app_name = 'events'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #url(r'^(?P<pk>[0-9]+)/event/$', views.EventView.as_view(), name='event'),
    #url(r'^(?P<pk>[0-9]+)/place/$', views.PlaceView.as_view(), name='place'),
]

Desktop/pilkanozna/ankiety/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

Desktop/pilkanozna/druzyna/urls.py
from django.conf.urls import url
from . import views

app_name = 'druzyna'

urlpatterns = [
    # /druzyna/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /druzyna/<druzyna_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'dodaj/$',views.TeamsCreate.as_view(), name='add-team'),

    #/druzyna/aktualizuj/1/
    url(r'aktualizuj/(?P<pk>[0-9]+)/$',views.TeamsUpdate.as_view(), name='update-team'),

    url(r'(?P<pk>[0-9]+)/usun/$',views.TeamsDelete.as_view(), name='delete-team'),

]

Desktop/pilkanozna/pilkanozna/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^druzyna/', include('druzyna.urls')),
    url(r'^zawodnik/', include('zawodnicy.urls')),
    url(r'^events/', include('Wydarzenia.urls')),
    url(r'^ankiety/', include('ankiety.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/pilkanozna/zawodnicy/urls.py
from django.conf.urls import url
from . import views

app_name = 'zawodnik'

urlpatterns = [
    # /zawodnik/
    url(r'^$', views.IndexView.as_view(), name='index_z'),

    #/zawodnik/id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'dodaj/$',views.PlayerCreate.as_view(), name='add-player'),
]

Desktop/pilkanozna/druzyna/models.py
from django.db import models
from django.core.urlresolvers import reverse
import django_tables2 as tables

class Druzyna(models.Model):
    nazwa = models.CharField(max_length=100)
    liga = models.CharField(max_length=100)
    kraj = models.CharField(max_length=50)
    trener = models.CharField(max_length=200)
    logo = models.FileField()


    def __str__(self):
        return self.nazwa


    def get_absolute_url(self):
        return reverse('druzyna:detail', kwargs={'pk': self.pk})

Desktop/pilkanozna/zawodnicy/models.py
from django.db import models
from django.core.urlresolvers import reverse
from druzyna.models import Druzyna


class Zawodnik(models.Model):
    druzyna = models.ForeignKey(Druzyna, on_delete=models.CASCADE)
    imie = models.CharField(max_length=50)
    nazwisko = models.CharField(max_length=70)
    wiek = models.IntegerField()
    wzrost = models.IntegerField()
    pozycja = models.CharField(max_length=70)
    numer = models.IntegerField()
    zdjecie = models.FileField()

    def __str__(self):
        return self.imie + '    ' + self.nazwisko

    def get_absolute_url(self):
        return reverse('zawodnik:detail', kwargs={'pk': self.pk})

Desktop/pilkanozna/druzyna/views.py
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Druzyna
from zawodnicy.models import Zawodnik


class IndexView(generic.ListView):
    template_name = 'druzyna/index.html'
    model = Zawodnik

    def get_queryset(self):
        return Druzyna.objects.all()


class DetailView(generic.DetailView):
    model = Druzyna
    template_name = 'druzyna/detail.html'


class TeamsCreate(CreateView):
    model = Druzyna
    fields = ['nazwa','liga','kraj','trener','logo']

class TeamsDelete(DeleteView):
    model = Druzyna
    success_url = reverse_lazy('druzyna:index')

class TeamsUpdate(UpdateView):
    model = Druzyna
    fields = ['nazwa', 'liga', 'kraj', 'trener', 'logo']

Desktop/pilkanozna/druzyna/templates/druzyna/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Start{% endblock %}</title>
    {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'druzyna/style.css' %} "/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="{% static 'druzyna/main.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'druzyna:index' %}"> Start </a>&nbsp;
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'druzyna:index'  %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Drużyny
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'zawodnik:index_z'  %}">
                        <span class="glyphicon glyphicon-list" aria-hidden="true"></span>&nbsp; Zawodnicy
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'events:index'  %}">
                        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp; Wydarzenia
                    </a>
                </li>
                </li>
                 <li class="">
                    <a href="{% url 'polls:index'  %}">
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Ankiety
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="">
            </div>
            <button type="submit" class="btn btn-default">Wyszukaj</button>
            </form>

            <ul class="nav navbar-nav navbar-right" >
                <li class="">
                    <a href="{% url 'druzyna:add-team' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Dodaj drużynę
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Wyloguj
                    </a>
                </li>

            </ul>

        </div>


    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

Desktop/pilkanozna/druzyna/templates/druzyna/detail.html
{% extends 'druzyna/base.html' %}
<head>
    <script src="{% static 'druzyna/jquery.tablesorter.min.js' %}"></script>
    <script  src="{% static 'druzyna/jquery-3.2.1.min.js' %}"></script>
</head>
<title>{% block title %}Szczegóły{% endblock %}</title>
{% block teams_active %}active{% endblock %}
<script type="text/javascript">
  $(document).ready(function()
    {
        $("#myTable").tablesorter();
    }
);

</script>


{% block body %}

<div class="container-fluid teams-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'druzyna:detail' druzyna.id %}">
                        {% if druzyna.logo %}
                            <img src="{{ druzyna.logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ druzyna.nazwa }} </h1>
                </div>
            </div>
        </div>

    <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'druzyna:update-team' druzyna.id %}">Aktualizuj</a></li>
                <li role="presentation"><a href="{% url 'zawodnik:add-player' %}">Dodaj zawodnika</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Wszyscy zawodnicy</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

     <table  id="myTable" class="tablesorter" >
     <thead>
        <tr>
            <th>Imię </th>
            <th>Nazwisko</th>
            <th>Pozycja</th>
            <th>Wiek</th>
            <th>Wzrost</th>
            <th>Numer</th>
        </tr>
     </thead>

         <tbody>
            {% for zawodnik in druzyna.zawodnik_set.all %}
                <thead>
                        <tr>
                            <th>&nbsp;{{ zawodnik.imie }} </th>
                            <th>&nbsp;{{ zawodnik.nazwisko }} </th>
                            <th>&nbsp;{{ zawodnik.pozycja }} </th>
                            <th>&nbsp;{{ zawodnik.wiek }} </th>
                            <th>&nbsp;{{ zawodnik.wzrost }} </th>
                            <th>&nbsp;{{ zawodnik.numer }} </th>
                            <br>
                        </tr>
                </thead>
            {% endfor %}
         </tbody>
    </table>

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Desktop/pilkanozna/druzyna/templates/druzyna/druzyna_form.html
{% extends 'druzyna/base.html' %}
<title>{% block title %}Dodaj drużynę{% endblock %}</title>
{% block teams_active %}active{% endblock %}

{% block body %}

<div class="container-fluid players-container">

    <div class="row">

        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'druzyna/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Zatwierdź</button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Desktop/pilkanozna/druzyna/templates/druzyna/form-template.html
{% for field in form %}
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small"> {{ field.errors }} </span>
        <div>
            <label class="control-label ">{{ field.label_tag }}</label>
            <div class="cm-sm-10">{{field }}</div>
        </div>
    </div>

    </div>
{% endfor %}

Desktop/pilkanozna/druzyna/templates/druzyna/index.html
{% extends 'druzyna/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="teams-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
        </div>
        {% if object_list %}
            {% for druzyna in object_list %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'druzyna:detail' druzyna.id %}">
                            <img src="{{ druzyna.logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ druzyna.nazwa }}</h2>

                            <!-- View Details -->
                            <a href="{% url 'druzyna:detail' druzyna.id %}" class="btn btn-primary btn-sm" role="button">Szczegóły</a>

                            <!-- Delete Album -->
                            <form action="{% url 'druzyna:delete-team' druzyna.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="druzyna_id" value="{{ druzyna.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                      </div>
                    </div>
                </div>

            {% endfor %}
    {% endif %}
    </div>
</div>
{% endblock %}