Desktop/pilkanozna/ankiety/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

Desktop/pilkanozna/pilkanozna/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^druzyna/', include('druzyna.urls')),
    url(r'^zawodnik/', include('zawodnicy.urls')),
    url(r'^events/', include('Wydarzenia.urls')),
    url(r'^ankiety/', include('ankiety.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/pilkanozna/ankiety/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def test_was_published_recently_with_old_question(self):
        """
        was_published_recently() should return False for questions whose
        pub_date is older than 1 day.
        """
        time = timezone.now() - datetime.timedelta(days=30)
        old_question = Question(pub_date=time)
        self.assertIs(old_question.was_published_recently(), False)


    def test_was_published_recently_with_recent_question(self):
        """
        was_published_recently() should return True for questions whose
        pub_date is within the last day.
        """
        time = timezone.now() - datetime.timedelta(hours=1)
        recent_question = Question(pub_date=time)
        self.assertIs(recent_question.was_published_recently(), True)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

Desktop/pilkanozna/ankiety/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_context_data(self, **kwargs):
        x = super(ResultsView, self).get_context_data(**kwargs)
        x['data'] = {'jeden': 1, 'dwa': 2, 'trzy': 3}
        return x


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Nie wybrales zadnej opcji.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

Desktop/pilkanozna/ankiety/templates/polls/detail.html
{% extends 'druzyna/base.html' %}
{% block body %}
            <div class="panel panel-default">
    <div class="panel-body">
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post"><br>
{% csrf_token %}
{% for choice in question.choice_set.all %}
   <font size="4"> <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
       <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br /></font>
{% endfor %}
<input type="submit" value="Glosuj" />
</form>
    </div></div>
{% endblock %}

Desktop/pilkanozna/ankiety/templates/polls/index.html
{% extends 'druzyna/base.html' %}
{% block body %}
        <div class="panel panel-default">
    <div class="panel-body">
{% if latest_question_list %}

    {% for question in latest_question_list %}
<center><li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li></center>
    {% endfor %}

    </div></div>
{% else %}
    <p>Brak ankiet.</p>
{% endif %}
{% endblock %}

Desktop/pilkanozna/ankiety/templates/polls/results.html
<script src="http://www.google.com/jsapi"></script>
<script src="/static/chartkick.js"></script>

{% extends 'druzyna/base.html' %}

{% block body %}

<center><h1>{{ question.question_text }}</h1></center>
<div class="panel panel-default">
    <div class="panel-body">
    <center>
{% for choice in question.choice_set.all %}

    <li><b><font size="4"> {{ choice.choice_text }}</b> -- {{ choice.votes }} </font> </li>

{% endfor %}
    </center>
</div>
</div>

    {% load chartkick %}
{% pie_chart data with height='200px' %}
    <br>

<tail><center><button><a href="{% url 'polls:index' %}">Powrot do ankiet</a></button></center></tail>
{% endblock %}